name: Generate docs from pod

on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    uses: Omochice/tataku-share-actions/.github/workflows/generate-doc.yml@3f21d8de919736a901cbfc3f042595a4cee2f2e8 # v2.0.31
    permissions:
      contents: write
      pull-requests: write
    secrets:
      APP_ID: ${{ secrets.PODENO_APP_ID }}
      PRIVATE_KEY: ${{ secrets.PODENO_PRIVATE_KEY }}
